#ifndef HW_ARM_PMB887X_DSP_SIGNALS_H
#define HW_ARM_PMB887X_DSP_SIGNALS_H

typedef enum pmb887x_dsp_gsm_signal_t pmb887x_dsp_gsm_signal_t;

enum pmb887x_dsp_gsm_signal_t {
	PMB887X_DSP_GSM_SIGNAL_EQON,
	PMB887X_DSP_GSM_SIGNAL_MONON,
	PMB887X_DSP_GSM_SIGNAL_SCON,
	PMB887X_DSP_GSM_SIGNAL_FCON,
	PMB887X_DSP_GSM_SIGNAL_RXON,
	PMB887X_DSP_GSM_SIGNAL_TXON,
	PMB887X_DSP_GSM_SIGNAL_CODON,
	PMB887X_DSP_GSM_SIGNAL_FRAME,
	PMB887X_DSP_GSM_SIGNAL_SYSMCU,
	PMB887X_DSP_GSM_SIGNAL_COUNT,
};

#endif
